Repository SoundCrate/scfront, pull requests merged in 2024-06, with the labels that each got.

#4 [ Annesa ] Post Review
  soundcrate/src/app/api/review/postReview/route.js
  soundcrate/src/app/api/user/getUser/[username]/route.js
  soundcrate/src/components/WriteReviewModal.js
  soundcrate/src/lib/models/review.js
Labels: enhancement

#5 [ Annesa ] Get Song Reviews
  soundcrate/src/app/album/[album_id]/page.js
  soundcrate/src/app/api/review/getReviews/route.js
  soundcrate/src/app/page.js
  soundcrate/src/app/song/[song_id]/page.js
  soundcrate/src/app/user/[username]/profile/albums/page.js
  soundcrate/src/app/user/[username]/profile/page.js
  soundcrate/src/app/user/[username]/profile/reviews/page.js
  soundcrate/src/app/user/[username]/song/[song_id]/page.js
  soundcrate/src/components/SongReviewCard.js
Labels: enhancement

#6 [ Annesa ] Like/Unlike Reviews
  soundcrate/src/app/api/review/likeReview/[reviewId]/route.js
  soundcrate/src/app/song/[song_id]/page.js
  soundcrate/src/app/user/[username]/profile/page.js
  soundcrate/src/app/user/[username]/profile/reviews/page.js
  soundcrate/src/app/user/[username]/song/[song_id]/page.js
  soundcrate/src/components/LikeButton.js
  soundcrate/src/components/SongReviewCard.js
Labels: enhancement

#7 [ Annesa ] Album Page
  soundcrate/src/app/album/[album_id]/page.js
  soundcrate/src/app/api/review/getReviews/route.js
  soundcrate/src/app/user/[username]/profile/page.js
  soundcrate/src/components/PrelineScript.js
  soundcrate/src/components/SongReviewCard.js
  soundcrate/src/lib/spotify.js
Labels: enhancement

#9 [ Annesa ] Home Page Backend
  soundcrate/src/app/page.js
Labels: enhancement

#11 [ Annesa ] Album Review Page
  soundcrate/src/app/user/[username]/album/[album_id]/page.js
Labels: enhancement

#15 [ Annesa ] Protected Actions Frontend + Backend
  soundcrate/src/app/ModalContextProvider/ModalContext.js
  soundcrate/src/app/ModalContextProvider/ModalContextProvider.js
  soundcrate/src/app/api/auth/[...nextauth]/route.js
  soundcrate/src/app/api/review/likeReview/[reviewId]/route.js
  soundcrate/src/app/api/review/postReview/route.js
  soundcrate/src/app/layout.js
  soundcrate/src/app/user/[username]/profile/reviews/page.js
  soundcrate/src/components/LikeButton.js
  soundcrate/src/components/ProtectedActionModal.js
  soundcrate/src/components/WriteReviewModal.js
  soundcrate/src/middleware.js
Labels: enhancement

#17 [ Annesa ] Sort Reviews by Likes
  soundcrate/src/app/api/review/getReviews/route.js
Labels: bug

#21 [ Annesa ] Protected Lists
  soundcrate/src/app/api/lists/createSongList/route.js
  soundcrate/src/app/api/lists/getListsBySong/route.js
  soundcrate/src/app/api/lists/getListsForModal/route.js
  soundcrate/src/app/api/lists/getSongLists/route.js
  soundcrate/src/app/api/lists/updateSongList/route.js
  soundcrate/src/app/song/[song_id]/page.js
  soundcrate/src/app/user/[username]/album/[album_id]/page.js
  soundcrate/src/app/user/[username]/list/[list_id]/page.js
  soundcrate/src/app/user/[username]/profile/lists/page.js
  soundcrate/src/app/user/[username]/profile/page.js
  soundcrate/src/app/user/[username]/song/[song_id]/page.js
  soundcrate/src/components/AddToListModal.js
  soundcrate/src/components/CreateListModal.js
  soundcrate/src/components/ListCard.js
  soundcrate/src/components/LoginForm.js
  soundcrate/src/components/NavBar.js
  soundcrate/src/components/RegisterForm.js
  soundcrate/src/middleware.js
Labels: bug, enhancement

#23 [ Annesa ] HSOverlay Fix
  soundcrate/src/app/song/[song_id]/page.js
  soundcrate/src/components/AddToListModal.js
  soundcrate/src/components/CreateListModal.js
  soundcrate/src/components/NavBar.js
  soundcrate/src/components/PrelineScript.js
  soundcrate/src/components/UpdateUserModal.js
  soundcrate/src/components/WriteReviewModal.js
Labels: bug

#27 [ Annesa ] Social Features
  soundcrate/src/app/api/review/getFollowingReviews/route.js
  soundcrate/src/app/api/user/searchByUsername/route.js
  soundcrate/src/app/feed/page.js
  soundcrate/src/app/search/page.js
  soundcrate/src/components/FollowBtn.js
  soundcrate/src/components/FollowUserCard.js
  soundcrate/src/components/NavBar.js
  soundcrate/src/middleware.js
Labels: enhancement

#26 [Jem] Adding UX/UI Options to Lists and the Profile Page
  .DS_Store
  soundcrate/jsconfig.json
  soundcrate/src/app/api/lists/createSongList/route.js
  soundcrate/src/app/api/lists/deleteSongList/route.js
  soundcrate/src/app/api/lists/editSongList/route.js
  soundcrate/src/app/api/lists/getSongLists/route.js
  soundcrate/src/app/song/[song_id]/page.js
  soundcrate/src/app/user/[username]/list/[list_id]/page.js
  soundcrate/src/app/user/[username]/profile/albums/page.js
  soundcrate/src/app/user/[username]/profile/lists/page.js
  soundcrate/src/app/user/[username]/profile/page.js
  soundcrate/src/app/user/[username]/profile/reviews/page.js
  soundcrate/src/app/user/[username]/song/[song_id]/page.js
  soundcrate/src/components/CreateListModal.js
  soundcrate/src/components/EditListModal.js
  soundcrate/src/components/EmptyContentMessage.js
  soundcrate/src/components/index.js
  soundcrate/src/lib/models/songList.js
Labels: bug, enhancement
